= Key New Features of Ansible Automation Platform 2.7
:navtitle: Home

== Introduction

Welcome to the Key New Features of *Ansible Automation Platform (AAP) 2.7 course!*. In this course, we will explore the major architectural changes, AI advancements and security enhancements being introduced in this release.

== Objectives

On completing this course, you should be able to:

✓ *Empower platform engineering*, and boost developer productivity

✓ *Drive automation adoption and scale* and eliminate friction

✓ *Unlock AI-driven automation*, turning intelligence into trusted action

The platform delivers improvements across *Efficiency | Resilience | Governance | Scale*

Duration: 30 minutes

== Prerequisites

To get the most out of this course, it is recommended that you have the basic understanding of Ansible Automation Platform and its components. Familiarity with automation concepts and practices will also be beneficial.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

- Andrius Benokraitis (Product Marketing Senior Manager)
- Rutuja Deshmukh (Content Architect)
- Anna Swicegood (Learning Product Manager)
- Amrinder Singh (Content Architect)